### ISSUE TITLE
editing a save results in messed up coordinates

### ISSUE THREAD

**Issue by MechtroYT** [Captainkittyca2/TMC-Save-Editor#1]

**Comment by Captainkittyca2** [comment]
Ah can you show me what were the coordinate issues you had specifically?

**Comment by MechtroYT** [comment]
So after editing a save and loading it in game you get stuck out of bounds

**Comment by MechtroYT** [comment]
and i also didnt touch the position values

**Comment by Captainkittyca2** [comment]
> So after editing a save and loading it in game you get stuck out of bounds

Ah yea, everytime you change the map in the save file, you also have to change the position values to a more appropriate position so he doesn't spawn inside a wall, for example
The best way to figure out coordinates so you don't spawn out of bounds is to use the [MinishMaker](https://github.com/minishmaker) tool (map editor) which allows you to open the maps of the game and view the coordinates

The way it works is, after you open the map in MinishMaker (green arrow) at the bottom left of MinishMaker's window, you'll see the coordinates of where you're mouse is (mouse: black arrow | coordinates: red arrows). In the save editor, you'll notice there's "big y" and "small y". In minishMaker, it only shows 2 values for y axis. Which means, for "big y" take the first value of the y coordinate in MinishMaker and convert it from hex to decimal (you can use a programming calculator to do that, there's a calculator app in windows that has a programming area) then after cnverting to decimal, input it to "big y" in save editor. As for "small y", take the 2nd value of the y coordinate in MinishMaker, and convert it to decimal, then input it to "small y" but it will be a 2 or 3 digit value, so if it's 3 in MinishMaker, you open a hex calculator and input a 2 digit value: you can put 30 or 31 or 32 etc (anywhere from 30 to 3F) then convert the hex value to decimal and input it in "small y". You do the same thing with x coordinates.

Example using below image:
In this example, i'm using Hyrule Town, room 1 map. the black arrow and the white square outline show you where i'm aiming my mouse in the image. After aiming my mouse in there, at the bottom left, the coordinates are: for x it's "1F" so in the save editor, for "big x", i inputed "1" and for "small x" i have to input a 2 digit value. So, in a hex calculator, I inputed "F" but not just "F", i inputed "F1 or F2 or F3, etc (anywhere from F0 to FF) then I converted it to decimal and inputed the decimal value in the save editor (in the screenshot below, I used F8 and converted it to decimal, which is 248)
![image](https://github.com/Captainkittyca2/TMC-Save-Editor/assets/68467449/7e93a0d1-7332-453e-942b-4863dc11bfac)

Unfortunately though, some maps, such as iirc, "Veil falls" don't work the same way so in minishmaker, it might give you a false value for coordinates.

**Comment by MechtroYT** [comment]
ok Thanks

**Comment by Captainkittyca2** [comment]
Btw, if you want to modify the save file but preserve the coordinates that you already had prior to saving, what you can do is: open your TMC save file in a hex editor (such as [HxD](https://mh-nexus.de/en/)) before opening it in the save editor and go to offsets 108 to 10B (108: coordinate Y big 109: Y small 10A: X big 10B: X small), then copy each of those values seperately and convert each to decimal value using a hex calculator, then input it in save editor

EDIT: If your save file is in file 2 or file 3 you have to do this for the offsets: 264 + (file number - 1) * 1280
And then convert the result to hex number and go to the offset (the offset you'll be in will be equivalent to offset 108)

**Comment by Captainkittyca2** [comment]
I'll have an option to preserve map info in the next update

**Comment by Captainkittyca2** [comment]
@MyUserNameIsVeryBad Sorry for late update. Can you test the [latest release](https://github.com/Captainkittyca2/TMC-Save-Editor/releases/tag/v0.2)?
When unchecking the "Customize" button, your coordinates should remain the same as well as the map you were in and the room. This time the spawn animations are modifiable regardless of whether or not you checked the "Customize" button.

**Comment by Captainkittyca2** [comment]
Alright well I tested myself and indeed it works
