### ISSUE TITLE
Unable to load Item menu

### ISSUE THREAD

**Issue by tyl0r** [Captainkittyca2/TMC-Save-Editor#2]
Hello, thank you for your work on this project.

I'm unable to access the Item/Status/Map menu via START button after loading the new save from the editor. Even if I don't alter anything in the interface, and simply save the file (overwriting the original save), it seems to make some changes to the save file.

Here's an example of what the editor changes (even though I don't specify any changes):

```
< 00000030: 4d43 5a33 4ab8 b548 ffff ffff ffff ffff  MCZ3J..H........
---
> 00000030: 4d43 5a33 f605 09fb ffff ffff ffff ffff  MCZ3............
24c24
< 00000170: 4554 4445 1155 0000 aa00 0000 0410 5500  ETDE.U........U.
---
> 00000170: 4554 4445 1000 0000 0000 0000 0410 5500  ETDE..........U.
```

[changed.eep.txt](https://github.com/user-attachments/files/16151048/changed.eep.txt)
[orig.eep.txt](https://github.com/user-attachments/files/16151049/orig.eep.txt)

Ultimately I'm trying to simply upgrade the Bow to Light Arrow Bow. I tried manually editing the hex and changing offset 173 to 50 or 51 in the save file but that didn't seem to change anything, the Item menu worked though. I'm guessing I need to also change something at 030.

Thanks

Let me know if I can provide anything else.

**Comment by obykin** [comment]
I was also just trying to upgrade the bow and came across the same exact issue. 

Left a comment on the video before finding this issue opened.
https://www.youtube.com/watch?v=HKjqNfzwfJg

Update: I tried using Beta 3 and the inventory menu works. Beta 4 re-introduced the inventory bug.

**Comment by Captainkittyca2** [comment]
Sorry for the late reply! Github didn't notify me about this issue so i only now noticed it. I'll look into it and try to fix it asap. Beta 3 was supposed to have fixed it but i guess i un-did the fix in beta 4 accidentally.

**Comment by Captainkittyca2** [comment]
You can use beta 3 for now until i fix the issue since beta 4 just makes it look normal in different computer screens

**Comment by Captainkittyca2** [comment]
also you can't edit the save file directly unless you edit the checksum value as well

**Comment by Captainkittyca2** [comment]
can you test with this? it should fix it. https://github.com/Captainkittyca2/TMC-Save-Editor/releases/tag/v0.4.5

**Comment by tyl0r** [comment]
yes, you're right about the checksum.

I just tested v0.4.5 and it works! thank you!
